#release configuration
#Tue Feb 03 16:58:06 WET 2026
project.dev.org.wildfly.core\:wildfly-subsystem-test-tests=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-testsuite-standalone=22.0.2.Final-ossnms-8-SNAPSHOT
projectVersionPolicyId=default
project.rel.org.wildfly.core\:wildfly-request-controller=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-embedded=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-model-test.empty=true
project.rel.org.wildfly.core\:wildfly-jar-boot=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-discovery=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-event-logger=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-management-client-content.empty=true
project.rel.org.wildfly.core\:wildfly-deployment-repository=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-testbom=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-model-test-controller-optional=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-dist.empty=true
project.dev.org.wildfly.core\:wildfly-core-feature-pack-parent=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-domain-http-interface.empty=true
project.dev.org.wildfly.core\:wildfly-platform-mbean=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-model-test.empty=true
project.scm.org.wildfly.core\:wildfly-domain-http.empty=true
project.dev.org.wildfly.core\:wildfly-threads=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-version=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-subsystem-test-framework=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-testsuite-shared=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-installation-manager=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-parent.developerConnection=scm\:git\:${wildfly.core.scm.connection}
project.scm.org.wildfly.core\:wildfly-discovery.empty=true
project.scm.org.wildfly.core\:wildfly-subsystem-test-parent.empty=true
project.rel.org.wildfly.core\:wildfly-core-testsuite-standalone=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-controller-client=22.0.2.Final-ossnms-7
scm.tag=wildfly-core-parent-22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-launcher=22.0.2.Final-ossnms-7
preparationGoals=clean verify
project.dev.org.wildfly.core\:wildfly-core-test-runner=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-feature-pack-parent.empty=true
project.dev.org.wildfly.core\:wildfly-core-management=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-testsuite-shared=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-controller=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-domain-management.empty=true
project.dev.org.wildfly.core\:wildfly-core-model-test-tests=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-subsystem-test-tests.empty=true
project.scm.org.wildfly.core\:wildfly-network.empty=true
project.scm.org.wildfly.core\:wildfly-core-build.empty=true
project.rel.org.wildfly.core\:wildfly-core-feature-pack-parent=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-security-manager=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-management-client=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-elytron-tool-wrapper=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-elytron-tool-wrapper.empty=true
project.rel.org.wildfly.core\:wildfly-core-testsuite-embedded=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-subsystem-test=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-domain-http-error-context.empty=true
project.rel.org.wildfly.core\:wildfly-remoting=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-subsystem-test-framework.empty=true
project.rel.org.wildfly.core\:wildfly-threads=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-deployment-repository.empty=true
project.dev.org.wildfly.core\:wildfly-io-tests=22.0.2.Final-ossnms-8-SNAPSHOT
scm.url=scm\:git\:git@github.com\:wildfly/wildfly-core.git
project.dev.org.wildfly.core\:wildfly-core-build=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-controller-client.empty=true
project.rel.org.wildfly.core\:wildfly-patching=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-model-test=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-host-controller=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-test-runner=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-patching.empty=true
project.scm.org.wildfly.core\:wildfly-core-model-test-tests.empty=true
project.scm.org.wildfly.core\:wildfly-script-tests.empty=true
project.dev.org.wildfly.core\:wildfly-controller-client=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-io-tests=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-jar-parent=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-io-tests.empty=true
project.rel.org.wildfly.core\:wildfly-io-bom=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-feature-pack-ee-10-api.empty=true
project.dev.org.wildfly.core\:wildfly-server=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-network=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-security=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-deployment-scanner=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-dist=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-feature-pack-ee-10-api=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-launcher.empty=true
project.dev.org.wildfly.core\:wildfly-security-manager=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-management-subsystem.empty=true
project.scm.org.wildfly.core\:wildfly-protocol.empty=true
project.rel.org.wildfly.core\:wildfly-remoting-test=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-server=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-controller=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-jar-runtime=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-elytron-integration.empty=true
project.rel.org.wildfly.core\:wildfly-domain-management=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-deployment-scanner.empty=true
project.dev.org.wildfly.core\:wildfly-patching=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-remoting-parent=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-feature-pack-common=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-domain-http-interface=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-model-test-framework.empty=true
project.rel.org.wildfly.core\:wildfly-protocol=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-security-manager.empty=true
project.dev.org.wildfly.core\:wildfly-core-model-test-framework=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-testbom=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-model-test-framework=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-remoting-test.empty=true
project.rel.org.wildfly.core\:wildfly-elytron-tool-wrapper=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-domain-management=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-request-controller=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-feature-pack-galleon-common=22.0.2.Final-ossnms-7
exec.additionalArguments=-DskipTests
scm.tagNameFormat=@{project.artifactId}-@{project.version}
project.scm.org.wildfly.core\:wildfly-core-component-matrix-builder.empty=true
project.rel.org.wildfly.core\:wildfly-platform-mbean=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-component-matrix-builder=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-discovery=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-parent=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-cli=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-launcher=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-testsuite-embedded.empty=true
project.rel.org.wildfly.core\:wildfly-script-tests=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-elytron-integration=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-testsuite.empty=true
project.dev.org.wildfly.core\:wildfly-core-testsuite-embedded=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-jar-boot.empty=true
project.scm.org.wildfly.core\:wildfly-threads.empty=true
project.rel.org.wildfly.core\:wildfly-installation-manager=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-protocol=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-testsuite-standalone.empty=true
project.rel.org.wildfly.core\:wildfly-process-controller=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-remoting-test=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-parent.connection=scm\:git\:${wildfly.core.scm.connection}
project.rel.org.wildfly.core\:wildfly-core-testsuite-elytron=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-feature-pack-common.empty=true
project.scm.org.wildfly.core\:wildfly-core-testbom.empty=true
project.dev.org.wildfly.core\:wildfly-core-galleon-pack=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-subsystem-test=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-logging=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-model-test=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-host-controller.empty=true
project.dev.org.wildfly.core\:wildfly-management-client-content=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-remoting-parent.empty=true
project.dev.org.wildfly.core\:wildfly-network=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-installation-manager.empty=true
project.scm.org.wildfly.core\:wildfly-core-security.empty=true
project.dev.org.wildfly.core\:wildfly-process-controller=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-jar-boot=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-testsuite-elytron=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-subsystem-test-tests=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-management=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-management-subsystem=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-embedded=22.0.2.Final-ossnms-8-SNAPSHOT
pushChanges=true
project.dev.org.wildfly.core\:wildfly-jar-runtime=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-parent.url=${wildfly.core.scm.url}
project.scm.org.wildfly.core\:wildfly-core-galleon-pack.empty=true
project.rel.org.wildfly.core\:wildfly-event-logger=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-version.empty=true
project.scm.org.wildfly.core\:wildfly-controller.empty=true
project.dev.org.wildfly.core\:wildfly-elytron-integration=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-component-matrix-builder=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-jar-parent.empty=true
project.rel.org.wildfly.core\:wildfly-domain-http-interface=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-management-subsystem=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-management.empty=true
project.dev.org.wildfly.core\:wildfly-jmx=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-model-test=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-build=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-io-bom=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-request-controller.empty=true
project.rel.org.wildfly.core\:wildfly-management-client-content=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-domain-http=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-jar-parent=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-host-controller=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-testsuite=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-feature-pack-ee-10-api=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-feature-pack-common=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-parent=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-model-test-controller-optional=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-core-management-client=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-testsuite-elytron.empty=true
project.rel.org.wildfly.core\:wildfly-jmx=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-dist=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-jar-runtime.empty=true
project.dev.org.wildfly.core\:wildfly-io=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-core-parent.tag=wildfly-core-parent-22.0.2.Final-ossnms-4-SNAPSHOT
scm.commentPrefix=[maven-release-plugin] 
project.rel.org.wildfly.core\:wildfly-core-model-test-tests=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-platform-mbean.empty=true
project.rel.org.wildfly.core\:wildfly-domain-http-error-context=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-testsuite=22.0.2.Final-ossnms-7
completedPhase=generate-release-poms
project.scm.org.wildfly.core\:wildfly-process-controller.empty=true
project.dev.org.wildfly.core\:wildfly-remoting=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-subsystem-test-parent=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-remoting.empty=true
project.scm.org.wildfly.core\:wildfly-embedded.empty=true
project.rel.org.wildfly.core\:wildfly-core-galleon-pack=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-subsystem-test.empty=true
project.scm.org.wildfly.core\:wildfly-core-management-client.empty=true
project.rel.org.wildfly.core\:wildfly-io=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-core-model-test=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-deployment-repository=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-event-logger.empty=true
project.scm.org.wildfly.core\:wildfly-core-testsuite-shared.empty=true
project.dev.org.wildfly.core\:wildfly-version=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-script-tests=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-subsystem-test-parent=22.0.2.Final-ossnms-8-SNAPSHOT
project.rel.org.wildfly.core\:wildfly-remoting-parent=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-domain-http-error-context=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-logging.empty=true
project.scm.org.wildfly.core\:wildfly-io.empty=true
remoteTagging=true
project.dev.org.wildfly.core\:wildfly-subsystem-test-framework=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-core-feature-pack-galleon-common=22.0.2.Final-ossnms-8-SNAPSHOT
project.dev.org.wildfly.core\:wildfly-cli=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-io-bom.empty=true
project.rel.org.wildfly.core\:wildfly-deployment-scanner=22.0.2.Final-ossnms-7
project.dev.org.wildfly.core\:wildfly-logging=22.0.2.Final-ossnms-8-SNAPSHOT
project.scm.org.wildfly.core\:wildfly-cli.empty=true
project.scm.org.wildfly.core\:wildfly-server.empty=true
project.scm.org.wildfly.core\:wildfly-core-feature-pack-galleon-common.empty=true
project.rel.org.wildfly.core\:wildfly-domain-http=22.0.2.Final-ossnms-7
project.rel.org.wildfly.core\:wildfly-core-security=22.0.2.Final-ossnms-7
project.scm.org.wildfly.core\:wildfly-core-test-runner.empty=true
project.scm.org.wildfly.core\:wildfly-jmx.empty=true
exec.snapshotReleasePluginAllowed=false
project.scm.org.wildfly.core\:wildfly-core-model-test-controller-optional.empty=true
